### ISSUE TITLE
[QUESTION] Update branch with rebase

### ISSUE THREAD

**Issue by mrpandat** [tibdex/autosquash#21]
Hi,

Thank you for this amazing bot !

I would like to know if there is a way to avoid the merge commit when autosquash update the branch. Can i specify the update method (like merge/rebase) in the configuration ?

Example: 
![image](https://user-images.githubusercontent.com/22916835/68478350-ecee9a80-022f-11ea-9aea-d3518eefc251.png)

Thank you :)

**Comment by tibdex** [comment]
Hi,

Autosquash uses the [same API](https://developer.github.com/changes/2019-05-29-update-branch-api/) GitHub calls when you click on the "Update branch" button and this endpoint only supports merge commits. There is a request to change that: https://github.com/isaacs/github/issues/1419 but it's unclear whether it will happen or not.

Anyway, I believe doing a merge commit is the right thing to do in that case (see [the README](https://github.com/tibdex/autosquash/tree/9151c7905017dfd2c4bd2bc3635553e8c61bacf7#why-squash-and-merge)) so even if this was possible I would probably stick to the current merge behavior. 

Why do you think a rebase, or another behavior would be best?

**Comment by mrpandat** [comment]
Hey,

Thanks for the quick reply !

In my case, we are 10+ developers on the project, and the CI take more than 30 minutes to finish , so sometimes we have to update the branch multiple times before it get merged, it means multiple merge update commit..

I think it would be nice to make this as an option (if https://github.com/isaacs/github/issues/1419 is ready).
