### ISSUE TITLE
Autosquash is merging PRs even if a review is pending

### ISSUE THREAD

**Issue by theor** [tibdex/autosquash#23]
![image](https://user-images.githubusercontent.com/1766559/68681302-2aee0600-0531-11ea-875b-2add3627a0b2.png)

It would be nice to wait for all pending reviews.

**Comment by tibdex** [comment]
Autosquash relies on the value of the [`MergeStateStatus`](https://developer.github.com/v4/enum/mergestatestatus/) to decide whether a pull request should be updated or merged. It won't attempt a merge if the status is blocked. And even if it did, GitHub should reject the request if the some [branch protections](https://help.github.com/en/github/administering-a-repository/about-protected-branches) are not satisfied.

Have you set up your branch protections correctly to enforce approved reviews from all the people you want?

**Comment by MaicolBen** [comment]
@tibdex Related question, can we configure not-auto merging?

**Comment by tibdex** [comment]
> can we configure not-auto merging?

What's your use case for not auto merging? Wouldn't it be enough then to not use Autosquash and just click on the "Update branch" button when you need it?

**Comment by MaicolBen** [comment]
> Wouldn't it be enough then to not use Autosquash and just click on the "Update branch" button when you need it?

I want a tool that does that automatically, otherwise, I have to keep updating the branch all day (we are 20 developers using the same repository). I guess I have to find something else, thank you!

**Comment by tibdex** [comment]
Hi Maicol, before changing anything in Autosquash, I'm trying to understand why do you need to update the branch several times a day if it's not for it to be merged as soon as it's ready. What do you get from doing that?

**Comment by MaicolBen** [comment]
80% of the cases, I want it to be merged as soon it's ready, but sometimes, I might want to have control when it's merged.

**Comment by tibdex** [comment]
Maybe then you could add the label only once you consider the PR to be good to be merged.

I'm trying to keep this repo zero-config and as simple as possible so I would like to wait for other people with a similar use case before adding the feature.

**Comment by MaicolBen** [comment]
Yes, you can forget this, I wanted a tool "auto-update" and I wasn't able to find one that works, so this is the best I got, thank you! Also, the code is clear, so I can disable this part in the future if I want.
