### ISSUE TITLE
Autosquash 2.0.2 not respecting the code owner protection rule

### ISSUE THREAD

**Issue by joce-unity** [tibdex/autosquash#27]
With the latest version, it seems that the code owner restriction is not considered when using autosquash.
We have the following restriction on our dev branch that uses autosquash:
![image](https://user-images.githubusercontent.com/59658317/72076410-7ddf0200-32c3-11ea-8633-61e45b7469f1.png)
Starting very recently (pretty confident that's when v 2.0.2 was rolled out), it seems that only having 2 reviewers was deemed enough even though no code owner singed off on the PRs.
And so the incoming PRs were let through, their branches merged to the dev branch and then deleted.
Pinning our usage to v 2.0.1 appears to get us rid of this unfortunate behavior.

**Comment by tibdex** [comment]
Hi, there has been no source code changes between 2.0.1 and 2.0.2 so I don't see what would lead Autosquash to not respect the Code Owners protection. Besides, Autosquash doesn't do anything particular concerning specific protections, it only relies on the [`MergeableState` property](https://github.com/tibdex/autosquash/blob/e1aaf3a813f7c67527abe52802fd94c6906ee694/src/autosquash.ts#L15-L25) computed by GitHub to detect if a PR is mergeable or not.
