### ISSUE TITLE
Only autosquash approved PR's

### ISSUE THREAD

**Issue by jacobrask** [tibdex/autosquash#28]
To avoid unnecessary merges and check runs, the search query for PR's could be updated to include `review:approved`. I'm not sure how this works in repositories that don't require approvals for merge, but perhaps the action could check *requiresApprovingReviews* and modify the query accordingly?

**Comment by OPeyrusse** [comment]
That could be interesting indeed. But at the same time, I see colleagues using autosquash to keep the PR in sync with the target branch.
If adding another Github Action to handle that, we could see conflicts between autosquash and this Action at the end when the PR is approved.
What do you think?

**Comment by OPeyrusse** [comment]
@tibdex your :+1: is confusing. Do you think:
 - we should have another action to merge PRs that are approved
 - that keeping the branch synced is a true feature and that it should be the job of autosquash?

I still think that merging only approved PRs is a good thing, that I saw countless times now. Maybe we should introduce a different configuration or another label to merge only when approved?
It can always be a new action, but it would be reusing much of the code of autosquash.

**Comment by OPeyrusse** [comment]
But from this comment [1] in #33, we say that the best practice is to label the PR at the end.
It makes me think that there are actually no reason for the flag at all. If autosquash should only merge validated PRs, then can't it run on every PR? When don't you want to have a PR not autosquash upon validation?

[1] https://github.com/tibdex/autosquash/issues/33#issuecomment-612511301

**Comment by tibdex** [comment]
> Only autosquash approved PRs [...] to avoid unnecessary merges and check runs

I prefer not coupling Autosquash with this specific approval condition and rather let projects configure the branch protections of their choice.

> If autosquash should only merge validated PRs, then can't it run on every PR? When don't you want to have a PR not autosquash upon validation?

When you work in a team and you reviewed and approved a PR but still requested some minor changes not worth another round of review. It lets the trusted author make these minor changes and merge the PR without further ado.
