### ISSUE TITLE
Support for custom labels?

### ISSUE THREAD

**Issue by madsnedergaard** [tibdex/autosquash#39]
Hey, love this action - it's have been using it for a month and it's working great!

I was wondering if there's any specific reason for the fixed/hardcoded label? 
If you're open to adding support for a custom label (declared in the workflow file) then I'd love to create a PR that does this.

**Comment by tibdex** [comment]
Thanks for the kind words. 

Adding an option for custom label would be easy but it would defeat a bit the "simple and opinionated" characteristics of of this action. I would rather keep it zero-config.

What's your use-case for custom labels?

**Comment by madsnedergaard** [comment]
I see your point, I was thinking it should use "autosquash" as default unless a custom label is set - but it's still adding more complexity :)

My use case was to use a name that is easier to understand for non-devs and align with our other labels.
