### ISSUE TITLE
Failing with 'Input required and not supplied: github_token' error

### ISSUE THREAD

**Issue by rwightman** [tibdex/autosquash#42]
I tried setting this up recently with a personal access token, ran into this error running the action. Pretty sure I set it up as per recommendations here. I did a search on github and looks like a few repositories there were succesfully using this at one point ran into the error and have removed the workflow as a result.

**Comment by tibdex** [comment]
Hi Ross,

Can you share your workflow file and the repos you mentioned?

Thanks.

**Comment by rwightman** [comment]
@tibdex mine is the default template, https://github.com/rwightman/pytorch-image-models/blob/master/.github/workflows/autosquash.yml

I created a personal access token with repo access, added it to secrets for the repository. I tried again with some more rights based on this issue https://github.com/tibdex/autosquash/issues/30

Attempt at using it: https://github.com/rwightman/pytorch-image-models/actions/runs/182599839

There is this instance of the error happening and attempt to fix it (not sure their attempt is correct..)
* https://github.com/ucalyptus/Spotify-Recommendation-Engine/issues/72

These guys look like they ran into some issues:
* https://github.com/software-mansion/react-native-reanimated/pull/863

**Comment by rwightman** [comment]
Woops

**Comment by romainr** [comment]
@rwightman Do you remember what was the issue?
